language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: melissari1997
    token: f8a947ecbc18a130578df1fb7d40d39039681071 # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
   - mvn verify -DfailIfNoTests=false sonar:sonar -Dsonar.projectKey=Melissari1997_openjpa 

